export const SET_EXCHANGE_ITEMS = 'SET_EXCHANGE_ITEMS'

export const SET_COURSES_LIST = 'SET_COURSES_LIST'

export const SET_UPDATE_COURSES_LIST = 'SET_UPDATE_COURSES_LIST'

export const SET_FETCH = 'SET_FETCH'

